global:
  projectID: opex-staging-b877
  isProduction: false
  computeNetworkSelfLink: https://www.googleapis.com/compute/v1/projects/opex-staging-b877/global/networks/gke-cluster
node-web-service:
  configuration: staging
  environment: opex-staging
  cloud-sql:
    instanceSuffix: a
  notesInstanceSuffix: b
