global:
  projectID: opex-prime-25d3
  isProduction: false
  computeNetworkSelfLink: https://www.googleapis.com/compute/v1/projects/opex-prime-25d3/global/networks/gke-cluster
node-web-service:
  configuration: prime
  environment: opex-prime
  cloud-sql: 
    instanceSuffix: a
  notesInstanceSuffix: a
